/**
 * Registry of available 60-day protocols.
 *
 * The default "Looksmax" program is defined in TypeScript; the six Phase 2
 * addiction-recovery programs are authored as data-driven JSON files in
 * `./protocols/*.json` (generated by `scripts/generate_protocols.py`). Because
 * everything reads protocols through the loader, the rest of the app never
 * needs to change when programs are added or edited.
 */
import type {
  AddictionType,
  ProtocolDefinition,
  ProtocolSummary,
} from "@/types/protocol";
import { looksmaxProtocol } from "./protocols/looksmax";

// Phase 2 recovery protocols (data-driven JSON in src/data/protocols → typed
// at import). Authored/regenerated by scripts/generate_protocols.py.
import alcoholRecovery from "@/data/protocols/alcohol-recovery.json";
import opioidRecovery from "@/data/protocols/opioid-recovery.json";
import weightLoss from "@/data/protocols/weight-loss.json";
import digitalDetox from "@/data/protocols/digital-detox.json";
import productivity from "@/data/protocols/productivity.json";
import generalHealth from "@/data/protocols/general-health.json";

/**
 * JSON is imported with inferred (loose) types; cast to the domain type. The
 * generator guarantees the shape, and protocolLoader.test.ts validates it.
 */
const recoveryProtocols: ProtocolDefinition[] = [
  alcoholRecovery,
  opioidRecovery,
  weightLoss,
  digitalDetox,
  productivity,
  generalHealth,
].map((p) => p as unknown as ProtocolDefinition);

/**
 * All registered protocols. Order here is the display order used by the
 * onboarding selector. Looksmax stays registered (it is the seeded default and
 * keeps the original experience intact) but is listed last.
 */
const ALL_PROTOCOLS: ProtocolDefinition[] = [
  ...recoveryProtocols,
  looksmaxProtocol,
];

/** All registered protocols keyed by id. */
const REGISTRY: Record<string, ProtocolDefinition> = Object.fromEntries(
  ALL_PROTOCOLS.map((p) => [p.id, p])
);

/** Default active program until the user chooses a track in onboarding. */
export const DEFAULT_PROTOCOL_ID = looksmaxProtocol.id;

/** Ids of the Phase 2 recovery tracks, in display order. */
export const RECOVERY_PROTOCOL_IDS = recoveryProtocols.map((p) => p.id);

export function getProtocolById(id: string): ProtocolDefinition | undefined {
  return REGISTRY[id];
}

function toSummary(p: ProtocolDefinition): ProtocolSummary {
  return {
    id: p.id,
    addictionType: p.addictionType,
    name: p.name,
    tagline: p.tagline,
    description: p.description,
    icon: p.icon,
    color: p.color,
    durationDays: p.durationDays,
  };
}

export function listProtocols(): ProtocolSummary[] {
  return ALL_PROTOCOLS.map(toSummary);
}

/** Only the six addiction-recovery tracks (excludes the default Looksmax). */
export function listRecoveryProtocols(): ProtocolSummary[] {
  return recoveryProtocols.map(toSummary);
}

/** Find the protocol that targets a given addiction type (first match). */
export function getProtocolByAddiction(
  type: AddictionType | string
): ProtocolDefinition | undefined {
  return ALL_PROTOCOLS.find((p) => p.addictionType === type);
}

export { REGISTRY as PROTOCOL_REGISTRY };
